# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
# ruff: noqa: E501
#
# Auto-generated by tune_triton_mla.py. Re-generate from the benchmark script
# when retuning sm120 fp8 MLA decode buckets.
"""Tuned per-bucket configs for TRITON_MLA decode on sm120 fp8 KV cache."""

from bisect import bisect_right


TUNED_KV_CONFIGS: dict[tuple[int, int, int], dict] = {
    (16, 16000, 1): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 8, "num_stages": 3, "num_warps": 4},
    (16, 16000, 2): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 16000, 4): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 16000, 8): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 16000, 16): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 16000, 32): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 16000, 64): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 16000, 128): {"num_kv_splits": 4, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 16000, 256): {"num_kv_splits": 2, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 64000, 1): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 8, "num_stages": 1, "num_warps": 8},
    (16, 64000, 2): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 64000, 4): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 64000, 8): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 64000, 16): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 64000, 32): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 64000, 64): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 64000, 128): {"num_kv_splits": 4, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 64000, 256): {"num_kv_splits": 2, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 128000, 1): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 8, "num_stages": 1, "num_warps": 8},
    (16, 128000, 2): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 128000, 4): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 128000, 8): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 128000, 16): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 128000, 32): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 128000, 64): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 128000, 128): {"num_kv_splits": 4, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 128000, 256): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 8},
    (16, 262144, 1): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 8, "num_stages": 1, "num_warps": 8},
    (16, 262144, 2): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 262144, 4): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 8},
    (16, 262144, 8): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 262144, 16): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 262144, 32): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 262144, 64): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 262144, 128): {"num_kv_splits": 4, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (16, 262144, 256): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 16000, 1): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 16000, 2): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 8},
    (64, 16000, 4): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 16000, 8): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 16000, 16): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 16000, 32): {"num_kv_splits": 4, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 16000, 64): {"num_kv_splits": 2, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 16000, 128): {"num_kv_splits": 1, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 16000, 256): {"num_kv_splits": 1, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 64000, 1): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 64000, 2): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 64000, 4): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 64000, 8): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 64000, 16): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 64000, 32): {"num_kv_splits": 4, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 64000, 64): {"num_kv_splits": 4, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 64000, 128): {"num_kv_splits": 2, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 64000, 256): {"num_kv_splits": 1, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 128000, 1): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 128000, 2): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 128000, 4): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 128000, 8): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 128000, 16): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 128000, 32): {"num_kv_splits": 8, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 128000, 64): {"num_kv_splits": 4, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 128000, 128): {"num_kv_splits": 2, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 128000, 256): {"num_kv_splits": 4, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 262144, 1): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 262144, 2): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 262144, 4): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 262144, 8): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (64, 262144, 16): {"num_kv_splits": 16, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 262144, 32): {"num_kv_splits": 8, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 262144, 64): {"num_kv_splits": 4, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 262144, 128): {"num_kv_splits": 8, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (64, 262144, 256): {"num_kv_splits": 4, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 16000, 1): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 8},
    (128, 16000, 2): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 16000, 4): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 16000, 8): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 16000, 16): {"num_kv_splits": 4, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 16000, 32): {"num_kv_splits": 2, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 16000, 64): {"num_kv_splits": 1, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 16000, 128): {"num_kv_splits": 1, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 16000, 256): {"num_kv_splits": 1, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 64000, 1): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 64000, 2): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 64000, 4): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 64000, 8): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 64000, 16): {"num_kv_splits": 4, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 64000, 32): {"num_kv_splits": 4, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 64000, 64): {"num_kv_splits": 2, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 64000, 128): {"num_kv_splits": 1, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 64000, 256): {"num_kv_splits": 2, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 128000, 1): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 128000, 2): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 128000, 4): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 128000, 8): {"num_kv_splits": 8, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 128000, 16): {"num_kv_splits": 8, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 128000, 32): {"num_kv_splits": 4, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 128000, 64): {"num_kv_splits": 2, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 128000, 128): {"num_kv_splits": 4, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 128000, 256): {"num_kv_splits": 2, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 262144, 1): {"num_kv_splits": 64, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 262144, 2): {"num_kv_splits": 32, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 262144, 4): {"num_kv_splits": 16, "BLOCK_N": 32, "BLOCK_H": 16, "num_stages": 1, "num_warps": 4},
    (128, 262144, 8): {"num_kv_splits": 16, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 262144, 16): {"num_kv_splits": 8, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 262144, 32): {"num_kv_splits": 4, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 262144, 64): {"num_kv_splits": 8, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 262144, 128): {"num_kv_splits": 4, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
    (128, 262144, 256): {"num_kv_splits": 2, "BLOCK_N": 16, "BLOCK_H": 32, "num_stages": 1, "num_warps": 4},
}


def _build_tuning_indexes() -> tuple[
    dict[int, tuple[int, ...]], dict[tuple[int, int], tuple[int, ...]]
]:
    mml_bucket_sets: dict[int, set[int]] = {}
    batch_bucket_sets: dict[tuple[int, int], set[int]] = {}
    for heads, mml, batch in TUNED_KV_CONFIGS:
        mml_bucket_sets.setdefault(heads, set()).add(mml)
        batch_bucket_sets.setdefault((heads, mml), set()).add(batch)
    return (
        {heads: tuple(sorted(mmls)) for heads, mmls in mml_bucket_sets.items()},
        {key: tuple(sorted(batches)) for key, batches in batch_bucket_sets.items()},
    )


_TUNED_MML_BUCKETS, _TUNED_BATCH_BUCKETS = _build_tuning_indexes()
del _build_tuning_indexes


def _floor_bucket(buckets: tuple[int, ...], value: int) -> int:
    idx = bisect_right(buckets, value) - 1
    if idx < 0:
        idx = 0
    return buckets[idx]


def lookup_config(q_num_heads: int, max_model_len: int, B: int) -> dict | None:
    """Return tuned config for (heads, max_model_len, B), else None."""
    if (q_num_heads, max_model_len, B) in TUNED_KV_CONFIGS:
        return TUNED_KV_CONFIGS[(q_num_heads, max_model_len, B)]

    mmls = _TUNED_MML_BUCKETS.get(q_num_heads)
    if mmls is None:
        return None
    mml = _floor_bucket(mmls, max_model_len)

    bs = _TUNED_BATCH_BUCKETS.get((q_num_heads, mml))
    if bs is None:
        return None
    b = _floor_bucket(bs, B)
    return TUNED_KV_CONFIGS.get((q_num_heads, mml, b))
